name: rudy.boyle
description: regional
version: 0.0.1
author: m9tevjgd.onqeb8sl@gquaeffh.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: rudyboyle
  parentArtefactID: ''
  buildSystem: maven
  author: null
  createdAt: '2025-02-05 06:21:40'
pipelines:
  pipelines/deletedOnLeftModifiedOnRightSelectLeft:
    name: deletedOnLeftModifiedOnRightSelectLeft
    description: Really solid info
    author: m9tevjgd.onqeb8sl@gquaeffh.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-02-05 06:21:40'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/deletedOnLeftModifiedOnRightSelectRight:
    name: deletedOnLeftModifiedOnRightSelectRight
    description: Really solid info
    author: m9tevjgd.onqeb8sl@gquaeffh.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-02-05 06:21:40'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/unModifiedPipeline:
    name: unModifiedPipeline
    description: Really solid info
    author: m9tevjgd.onqeb8sl@gquaeffh.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-02-05 06:21:41'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-02-05 06:21:40'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-02-05T06:21:40.461785Z'
  name: plibMaven
  version: 8.9.0-SNAPSHOT
  id: '2038146343'
  createdAt: '2025-02-05T06:21:40.461785Z'
  type: plibMaven
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
